version: '3'

services:
  db:
    build: ./mysql-review

  logger-mongodb:
    build: ./logger-mongodb
    ports:
      - '27017:27017'

  server:
    build: ./node-server
    ports:
      - '5000:5000'
    depends_on:
      - db
      - logger-mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    restart: on-failure
    links:
      - logger-mongodb
